apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
- banner-data.yaml
- link-demo.yaml

# RHOAI demo w/ gpu autoscaling
- https://github.com/codekow/demo-ai-gitops-catalog/demos/rhods-nvidia-gpu-autoscale

# Dev Spaces w/ gpu autoscaling
- https://github.com/codekow/demo-ai-gitops-catalog/demos/devspaces-nvidia-gpu-autoscale

# OpenShift Web Terminal
- https://github.com/codekow/demo-ai-gitops-catalog/components/operators/web-terminal/operator/overlays/fast
- web-terminal-tooling.yaml

patches:
  - target:
      kind: ConsoleNotification
      name: banner-demo
    patch: |-
      - op: replace
        path: /spec/text
        value: 'DEMO: Dell CSC Lab'
