apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# RHOAI demo w/ gpu autoscaling
- https://github.com/codekow/demo-ai-gitops-catalog/demos/rhods-nvidia-gpu-autoscale

patches:
  - target:
      kind: ConsoleNotification
      name: banner-demo
    patch: |-
      - op: replace
        path: /spec/text
        value: 'DEMO: RHOAI w/ OCR'
